--CREATE DATABASE SQLINTRO

--USE SQLINTRO

CREATE TABLE REGIONS
(
ID INT,
NAME NVARCHAR(20),

)

CREATE TABLE COUNTRIES(
COUNTRY_ID INT,
COUNTRY_NAME NVARCHAR(40),
REGION_ID INT)

CREATE TABLE LOCATIONS(
LOCATION_ID INT,
STREET_ADRESS NVARCHAR(25),
POSTAL_CODE NVARCHAR(12),
CITY NVARCHAR,
STATE_PROVINCE VARCHAR(12),
COUNTRY_ID INT)


CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID INT,
DEPARTMENT_NAME NVARCHAR(30),
MANAGER_ID INT,
LOCATION_ID INT)

CREATE TABLE JOB_HISTORY(
EMPLOYE_ID INT,
START_DATE DATE,
END_DATE  DATE,
JOB_ID VARCHAR,
DEPARTMENT_ID INT)

CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INT,
FIRST_NAME NVARCHAR(20),
LAST_NAME NVARCHAR(25),
EMAIL NVARCHAR(25),
PHONE_NUMBER VARCHAR(20),
HIRE_DATE DATE,
JOB_ID VARCHAR,
SALARY FLOAT,
COMMISION_PCT INT,
MANAGER_ID INT,
DEPARTMENT_ID INT)


CREATE TABLE JOBS(
JOB_ID VARCHAR,
JOB_TITLE NVARCHAR(35),
MIN_SALARY FLOAT,
MAX_SALARY FLOAT)





